### ISSUE TITLE
improved annotations

### ISSUE THREAD

**Issue by soongyuu** [Li-Chengyang/MSDS-RCNN#11]
Hi,Your work is very valuable.I had some problems with the experiment. The link to improved testing annotations is unavailable.Hope the author can update, thank you.Where can I get improved training annotations?

**Comment by shweta112** [comment]
@soongyuu You can find the training annotations [here](https://li-chengyang.github.io/home/MSDS-RCNN/) under the Downloads section. For the improved testing annotations by Liu et al, you'll need to fill the Google form [here](https://docs.google.com/forms/d/e/1FAIpQLSe65WXae7J_KziHK9cmX_lP_hiDXe7Dsl6uBTRL0AWGML0MZg/viewform?entry.1637202210&entry.1381600926&entry.718112205&entry.233811498) and you should receive the link to download them in your mail.

**Comment by LewX** [comment]
same issue, can you share the  improved training annotations? thanks a lot!
